import { card } from './card.mjs';
import { checkedAt, discount, escapeHtml, money, placeholder, productImage } from './layout.mjs';

export const home = ({ deals, categories, affiliateTag }) => {
  const live = deals.filter((deal) => deal.status === 'live');
  const featured = live.filter((deal) => deal.featured).sort((a, b) => (discount(b) || 0) - (discount(a) || 0))[0];
  const byCategory = (category) => live.filter((deal) => deal.category === category.slug);
  const orderedCategories = [...categories].sort((a, b) => Math.max(...byCategory(b).map(discount)) - Math.max(...byCategory(a).map(discount)));
  return `<section class="hero"><div class="shell hero-grid"><div class="hero-copy"><p class="eyebrow">Today’s featured drop</p><h1>${escapeHtml(featured.title)}</h1><p class="hero-summary">${escapeHtml(featured.summary)}</p><div class="price-block price-block--hero"><strong>${money(featured.price)}</strong><s>${money(featured.listPrice)}</s><span>${discount(featured)}% off</span></div><p class="checked">Checked ${checkedAt(featured.verifiedAt)}</p><a class="button" href="https://www.amazon.com/dp/${featured.asin}?tag=${affiliateTag}" rel="nofollow sponsored">View on Amazon</a></div><div class="hero-image">${productImage(featured)}<span class="price-tag">${discount(featured)}% off</span></div></div></section><section class="shell section"><div class="section-heading"><div><p class="eyebrow">Browse the desk</p><h2>Shop by category</h2></div></div><div class="category-tiles">${categories.map((category) => `<a class="category-tile category-tile--${category.slug}" href="/c/${category.slug}/"><span>${placeholder(category.slug)}</span><strong>${category.name}</strong><small>${byCategory(category).length} ${byCategory(category).length === 1 ? 'deal' : 'deals'}</small></a>`).join('')}</div></section><section class="shell section"><div class="section-heading"><div><p class="eyebrow">Editorial order</p><h2>Top picks</h2></div></div>${orderedCategories.map((category) => `<div class="pick-row"><div class="subheading"><h3>${category.name}</h3><a href="/c/${category.slug}/">See all <span aria-hidden="true">→</span></a></div><div class="deal-grid pick-grid">${byCategory(category).sort((a, b) => a.pickRank - b.pickRank).slice(0, 4).map((deal) => card(deal, categories)).join('')}</div></div>`).join('')}</section><section class="shell section"><div class="section-heading"><div><p class="eyebrow">Sorted by discount</p><h2>Biggest cuts today</h2></div></div><div class="deal-grid">${live.filter((deal) => deal.listPrice).sort((a, b) => discount(b) - discount(a)).slice(0, 8).map((deal) => card(deal, categories)).join('')}</div></section><aside class="trust-strip"><div class="shell">Every price is checked by hand and timestamped. We earn a commission if you buy through our links. <a href="/disclosure/">Disclosure</a></div></aside>`;
};
